author:
  name: Fernando Tricas García
  url: https://elmundoesimperfecto.com/
  email: projects@elmundoesimperfecto.com
  avatar: https://1.gravatar.com/avatar/16fefa5bbee207e96c9d78ad3854995c28c0ac2ef959889e8fea717b6a88f286
  homepage: https://elmundoesimperfecto.com/
footer-links:
  email: projects@elmundoesimperfecto.com
  facebook: fernando.tricas
  github: fernand0
  instagram: ftricas
  linkedin: fernand0
  twitter: fernand0
  mastodon: https://mastodon.social/@fernand0
  bluesky: fernand0.bsky.social
tagline: Proyectos de software y tecnología
explanation: Bots, herramientas CLI, plugins y más.
plugins:
- jekyll-feed
theme_color: theme-base-0b2
theme_version: 1.0.0
title: Projects // Proyectos
email: projects@elmundoesimperfecto.com
description: 'Colección de proyectos de software, bots, herramientas CLI y plugins
  desarrollados con Python, Vim, Errbot y otras tecnologías.

  '
markdown: kramdown
collections:
  projects:
    output: true
    permalink: /:title
